    export const env = {
    NEXT_PUBLIC_BACKEND_DOMAIN: process.env.NEXT_PUBLIC_BACKEND_DOMAIN,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_TOUR_PLUGIN_DOMAIN: process.env.NEXT_PUBLIC_TOUR_PLUGIN_DOMAIN,
    NEXT_PUBLIC_IMAGE_DOMAINS: process.env.NEXT_PUBLIC_IMAGE_DOMAINS,
    NEXT_PUBLIC_API_CHATBOT_URL: process.env.NEXT_PUBLIC_API_CHATBOT_URL,
    NEXT_PUBLIC_API_CMS_URL: process.env.NEXT_PUBLIC_API_CMS_URL,
    NEXT_PUBLIC_API_HOTEL_URL: process.env.NEXT_PUBLIC_API_HOTEL_URL,
    NEXT_PUBLIC_API_FILE_URL: process.env.NEXT_PUBLIC_API_FILE_URL,
    NEXT_PUBLIC_API_USER_URL: process.env.NEXT_PUBLIC_API_USER_URL,
    NEXT_PUBLIC_API_AUTH_URL: process.env.NEXT_PUBLIC_API_AUTH_URL,
};
