export const env = {
    NEXT_PUBLIC_BACKEND_DOMAIN: process.env.NEXT_PUBLIC_BACKEND_DOMAIN,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_TOUR_STATIC_BASE_URL: process.env.NEXT_PUBLIC_TOUR_STATIC_BASE_URL,
    NEXT_PUBLIC_TOUR_PLUGIN_DOMAIN: process.env.NEXT_PUBLIC_TOUR_PLUGIN_DOMAIN,
    NEXT_PUBLIC_IMAGE_DOMAINS: process.env.NEXT_PUBLIC_IMAGE_DOMAINS,
};
